[package]
name = "hpcprofiler"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.30", features = ["derive"] }
console = "0.15.10"
console-utils = "1.6.1"
inquire = "0.7.5"
ratatui = "0.29.0"
youchoose = "0.1.1"
